Adjust CI/CD workflow for Plugins

diff --git a/.github/workflows/gcp_plugins.yml b/.github/workflows/gcp_plugins.yml
--- a/.github/workflows/gcp_plugins.yml
+++ b/.github/workflows/gcp_plugins.yml
@@ -3,10 +3,16 @@ name: Deploy Plugins to Cloud RUN
 # TODO: determine if changes to backend folder before pushing
 
 on:
-  push:
-    branches: [ "main", "development" ]
-    paths:
-      - 'plugins/**'
+  workflow_dispatch:
+    inputs:
+      environment:
+        description: 'Select the environment to deploy to'
+        required: true
+        default: 'development'
+      branch:
+        description: 'Branch to deploy from'
+        required: true
+        default: 'main'
 
 env:
   SERVICE: plugins
@@ -14,15 +20,28 @@ env:
 
 jobs:
   deploy:
-    environment: ${{ (github.ref == 'refs/heads/development' && 'development') || (github.ref == 'refs/heads/main' && 'prod') }}
+    environment: ${{ github.event.inputs.environment }}
     permissions:
       contents: 'read'
       id-token: 'write'
 
     runs-on: ubuntu-latest
     steps:
+      - name: Validate Environment Input
+        run: |
+          if [[ "${{ github.event.inputs.environment }}" != "development" && "${{ github.event.inputs.environment }}" != "prod" ]]; then
+            echo "Invalid environment: ${{ github.event.inputs.environment }}. Must be 'development' or 'prod'."
+            exit 1
+          fi
+
+      # To workaround "no space left on device" issue of GitHub-hosted runner
+      - name: Delete huge unnecessary tools folder
+        run: rm -rf /opt/hostedtoolcache
+
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.branch }}
 
       - name: Google Auth
         id: auth
